---
- name: Backup running configuration
  hosts: routers
  gather_facts: false
  vars:
    student_id: "66070014"
    output_file: "{{ playbook_dir }}/show_run_{{ student_id }}_{{ inventory_hostname }}.txt"
  tasks:
    - name: Collect running configuration
      ansible.netcommon.cli_command:
        command: show running-config
      register: show_run

    - name: Save running configuration locally
      ansible.builtin.copy:
        dest: "{{ output_file }}"
        content: "{{ show_run.stdout if show_run.stdout is string else show_run.stdout[0] }}"
        mode: "0644"
      delegate_to: localhost
      run_once: true